version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clevertec
    ports:
      - 5432:5432

  app:
    build: ./
    container_name: java_app
    ports:
      - 9080:9080